version: "2.1"
services:
  opbeans-java:
    build: .
    image: opbeans/opbeans-java:latest
    ports:
    - "127.0.0.1:${OPBEANS_SERVER_PORT:-8000}:8000"
    logging:
      driver: 'json-file'
      options:
        max-size: '2m'
        max-file: '5'
    environment:
    - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-opbeans-java}
    - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-http://apm-server:8200}
    - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN}
    - ELASTIC_APM_JS_SERVER_URL=${ELASTIC_APM_JS_SERVER_URL:-http://localhost:${OPBEANS_SERVER_PORT:-8000}}
    - OPBEANS_SERVER_PORT=${OPBEANS_SERVER_PORT:-8000}
    healthcheck:
      test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://opbeans-java:8000/"]
      interval: 10s
      retries: 10
