apiVersion: v1
kind: Pod
metadata:
  name: kibana
  labels:
    app: kibana
    tier: frontend
spec:
  containers:
  - name: kibana
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
    - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  type: NodePort
  ports:
  - port: 5601
    nodePort: 30601
  selector:
    app: kibana
    tier: frontend
---
